blog/urls.py
from django.urls import path
from .views import PostListView, PostCreateView, AboutView


app_name = 'blog'
urlpatterns = [
    path('', PostListView.as_view(), name='home'),
    path('add-post/', PostCreateView.as_view(), name='add-post'),
    path('about/', AboutView.as_view(), name='about'),
]

foxymoron/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('accounts/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', TemplateView.as_view(template_name='home.html')),
    
]

users/urls.py
from django.urls import include, path
from .views import SignupView


urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('signup/', SignupView.as_view(), name='signup' ),
]

blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    author = models.CharField(max_length=100)
    published = models.DateField(auto_now_add=True)
    edited = models.DateField(auto_now=True)

    def __str__(self):
        return self.title



class Wish(models.Model):
    quote = models.TextField()
    quotee = models.CharField(max_length=100)
    published = models.DateField(auto_now_add=True)
    

    def __str__(self):
        return self.quotee

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from .managers import CustomUserManager


class CustomUser(AbstractUser):
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(_('email address'), unique=True)
    mpishi = models.BooleanField(default=False)
    mteja = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = CustomUserManager()

    def __str__(self):
        return self.username

blog/forms.py
from django.forms import ModelForm
from .models import Post, Wish

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title','body', 'author']




class WishForm(ModelForm):
    class Meta:
        model = Wish
        fields = ['quote','quotee']
        labels={
            'quote':'wish',
            'quotee':'your secret name'
        }

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('email','username',)


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email','username',)

blog/views.py
from django.shortcuts import render
from .models import Post
from .forms import PostForm, WishForm
from django.views.generic import ListView, CreateView, TemplateView
# Create your views here.

class PostListView(ListView):
    
    allow_empty = True 
    model = Post
    template_name = 'blog/post-list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.all()
        return context



class PostCreateView(CreateView):
    # model = Post
    form_class = PostForm
    template_name = 'blog/add-post.html'
    success_url = '/' 


class AboutView(TemplateView):
    template_name = 'blog/about.html'

users/views.py
from django.shortcuts import redirect
from django.contrib.auth import login
from django.views.generic import CreateView
from .models import CustomUser
from .forms import CustomUserCreationForm
# Create your views here.


class SignupView(CreateView):
    model = CustomUser
    form_class = CustomUserCreationForm
    template_name = 'registration/signup_form.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('blog: home')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>FOXYMORON</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block style %}
    {% endblock %}
</head>
<body>
    <header>
        <div class="brand-toggle">
            <span id="brand">F</span>
            <span id="toggle">on/off</span>
        </div>
        <nav class="nav">
            <ul>
                <li><a href="#">moja</a></li>
                <li><a href="#">moja mbili</a></li>
                <li><a href="#">moja</a></li>
            </ul>
        </nav>
    </header>
    {% block content %}
    {% endblock  %}
</body>
</html>

templates/blog/about.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet"> 
    <link rel="stylesheet" href="">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>FOXYMORON</title>
    <script src="https://kit.fontawesome.com/c6cb20e38a.js"></script>


    <style>
        #about-container{
            display: flex;
            justify-content: center;
        }

        #about{
            width: 60vh;
        }

        #about-id{
            width: 60vh;
            display:flex;
            justify-content: space-around;
            align-items: center;
            
        }

        #about-id-image{
            height:150px;
            width:150px;
            border: solid 1.5px #af9029;
            border-radius:50%;
        }
        #about-id-name{
            text-align: center;
        }
        #about-caption{
            text-align:left;
            padding:4%;
        }

        #about-links{
            display:flex;
            flex-direction: column;
            justify-content: space-around;
        }

        #about-links span i{
            font-size: 3rem;
        }

        .about-links-details{
            display:flex;
            flex-direction: row;
            justify-content: space-between;
            padding: 4% 4% 4% 4%;
            
        }
        .detail{
            color: #af9029;
        }
    </style>
</head>
<body class='light-mode'>
    <header style="height:20vh;">
        <nav>
            <span id="brand">
                F
                <!-- <span id="mode-switch" ></span> -->
            </span>
            <span id="mode-switch" class='mode-switch-dark'>dark mode</span>
            <ul>
                <li>
                    <a href="{% url 'blog:home' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'blog:about' %}">About</a>
                </li>
                {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'blog:add-post' %}">Add Post</a>
                    </li>
                    <li>
                        <a href="{% url 'logout' %}">Logout</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </header>
        
    <main id="about-container">
        <div id="about">

            <div id="about-id">
                <img id='about-id-image' src="{% static 'images/img.jpg' %}" alt="">
                <h2 id="about-id-name" style="font-weight:700;">NEWTON MUSYANI</h2>
                
            </div>
            <div id="about-caption" >
                <br><br>
                I write to express myself. I code to create.
                <br> <br>
                I make seriously cool websites, secure and stylish mobile and web apllications 
                and I can make sure your online product gets the highest possible exposure online.
                <br> <br>
                Let's talk:
                <br><br><br>
            </div>
            <div id="about-links">
                <div class="about-links-details">
                        <span>
                                <i class="fas fa-phone-square"></i>
                                <!-- &nbsp; &nbsp; -->
                                <br>
                                <b class="detail">+255 784 20 52 32</b>
                            </span>
            
                            <span>
                                <i class="fab fa-whatsapp-square"></i>
                                <!-- &nbsp; &nbsp; -->
                                <br>
                                <b class="detail">+255 784 20 52 32</b>
                            </span>
                </div>

                <div class="about-links-details">
                        <span>
                                <i class="fas fa-envelope-square"></i>
                                <!-- &nbsp; &nbsp; -->
                                <br>
                                <b class="detail">morandevelopers@gmail.com</b>
                            </span>
            
                            <span>
                                    <i class="fab fa-github-square"></i>
                                <!-- &nbsp; &nbsp; -->
                                <br>
                                <a href="https://github.com/Morandevs" style="text-decoration:none; color:black;">
                                    <b class="detail">
                                        Github &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</b>
                                </a>
                            </span>
                </div>
                
            </div>

            

            

        </div>
       
    </main>
    <!-- <hr style="width:40vw; color:#af9029"> -->
    <br>
    <br>
    <footer>
       
    </footer>

    
    
    <script src="{% static 'js/index.js' %}"></script>
</body>
</html>

templates/blog/add-post.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <title>Add post</title>
    <style>
        /* Extra small devices (phones, 600px and down) */
 @media only screen and (max-width: 600px) {

    form{
        margin-top: 10%;
        margin-left: 10%;
        width:80%;
    }
    
         
 }

         /* Small devices (portrait tablets and large phones, 600px and up) */
 @media only screen and (min-width: 600px) {
    form{
        margin-top: 10%;
        margin-left: 10%;
        width:80%;
    }
    
 }
 
 /* Medium devices (landscape tablets, 768px and up) */
 @media only screen and (min-width: 768px) {
    
    form{
        margin-top: 10%;
        margin-left: 40%;
        width:20%;
    }
    
         
 }

        
    </style>
</head>
<body>
    <div>
            <form action="" method="POST">
                    {%csrf_token%}
                {{form.as_p}}
                <input type="submit" value="Log in">
            </form>
    </div>
    
</body>
</html>

templates/blog/add-wish.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <title>Add post</title>
    <style>
        /* Extra small devices (phones, 600px and down) */
 @media only screen and (max-width: 600px) {

    form{
        margin-top: 10%;
        margin-left: 10%;
        width:80%;
    }
    
         
 }

         /* Small devices (portrait tablets and large phones, 600px and up) */
 @media only screen and (min-width: 600px) {
    form{
        margin-top: 10%;
        margin-left: 10%;
        width:80%;
    }
    
 }
 
 /* Medium devices (landscape tablets, 768px and up) */
 @media only screen and (min-width: 768px) {
    
    form{
        margin-top: 10%;
        margin-left: 40%;
        width:20%;
    }
    
         
 }

        
    </style>
</head>
<body>
    <div>
            <form action="" method="POST">
                    {%csrf_token%}
                {{form.as_p}}
                <input type="submit" value="Send Message">
            </form>
    </div>
    
</body>
</html>

templates/blog/post-list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% comment %} <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">  {% endcomment %}
    <link rel="stylesheet" href="">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"> <!--temporary-->
    <title>FOXYMORON-dev</title>
</head>
<body class='dark-mode'>
    <header>
        <nav>
            <span id="brand">
                F
                <!-- <span id="mode-switch" ></span> -->
            </span>
            <span id="mode-switch" class='mode-switch-light' ></span>
            <ul>
                <li>
                    <a href="{% url 'blog:home' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'blog:about' %}">About</a>
                </li>
                {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'blog:add-post' %}">Add Post</a>
                    </li>
                    <li>
                        <a href="{% url 'logout' %}">Logout</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
        <div id="poster">
            <span id="poster-text">
                FOXYMORON
                
            </span>
            <span>Musings of a Tanzanian dreamer</span>
        </div>
    </header>
        
    <main>
    <span class="invisible"  id="butt">
                ^
            </span>
    
    <div class="grid">
            {% for post in posts %}
        <div class="box box-stub">
            <div class="main-post">
                <h2>{{post.id}}. {{post.title}}</h2>

                <p>
                {{post.body | linebreaks}}
                <br/>
                <span>
                    -{{post.author}}
                    <hr style="width:4vw; color:#af9029">
                </span>
                </p>

            </div>
        </div>
        {% endfor %}
    </div>
    

               
    </main>
    <hr style="width:40vw; color:#af9029">
    <br>
    <br>
    <footer>
        <div id='disclaimer'>
                <h3 style='text-align:center'>DISCLAIMER</h3>
                <p>
            All the information on this website is published
            in good faith and for general information purpose
                only. Foxymoron does not make any warranties
                about the completeness, reliability and accuracy
                of this information. Any action you take upon 
                the information you find on this website
                , is strictly at your own risk. will not be liable for
                any losses and/or damages in connection with the use of our website.

                </p>
                <p>
                From our website, you can visit other websites 
                by following hyperlinks to such external sites. 
                While we strive to provide only quality links 
                to useful and ethical websites, we have no control
                    over the content and nature of these sites. These 
                    inks to other websites do not imply a recommendation 
                    for all the content found on these sites. Site owners
                    and content may change without notice and may occur 
                    before we have the opportunity to remove a link which may have gone ‘bad'.
                    
                </p>
                <p>
                Please be also aware that when you leave our website, 
                other sites may have different privacy policies and
                    terms which are beyond our control. Please be sure to 
                    check the Privacy Policies of these sites as well as their
                    "Terms of Service" before engaging in any business
                    or uploading any information
                </p>

                <div style='display:flex; justify-content:end;'>
                        <a href="{% url 'login' %}" id="admin-link"style='text-decoration:none'>Not Confidential</a>
                    </div>
        </div>
    </footer>

    
     <script>                                                                                                                                                                                                                                                                
        
        let paras = document.getElementsByClassName('invisible');

        for(i=0;i<paras.length; i++){
            console.log(paras.item(i));
        }
    
    </script>

    <script src="{% static 'js/index.js' %}"></script>
   
</body>
</html>

templates/home.html
{% extends "base.html" %}

{%  block style %}

{% endblock %}